# Site settings
title: Romke van der Meulen
email: romke.vd.meulen@gmail.com
description: A Dutch student of Man and Machine, Science and Faith, Philosophy and Life.
baseurl: ""
url: "http://romkevandermeulen.nl"
twitter_username: RomkeVdMeulen
github_username:  RomkeVdMeulen

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jemoji

exclude: [nbproject]

# Homepage
paginate: 50

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      comments: true
